import React, {FC} from 'react';

import {DocContainer, DocImage} from 'components';

import BlockchainHalted from './BlockchainHalted.png';
import HaltRequested from './HaltRequested.png';
import LastStep from './LastStep.png';
import LongestBlockchain from './LongestBlockchain.png';
import ScheduleAdjustments from './ScheduleAdjustments.png';
import SyncingBlockchains from './SyncingBlockchains.png';

const GuideScheduleAdjustments: FC = () => {
  return (
    <DocContainer className="GuideScheduleAdjustments" title="Schedule Adjustments" lastUpdated="23 Apr 2021">
      <p>
        At the end of each turn the responsibility of PV will transition to the next validator on the schedule. Each
        validator is only able to generate blocks as PV during their scheduled time. Any blocks generated outside a
        validators time as PV will be deemed invalid by the CVs.
      </p>
      <p>
        If a malicious block is ever generated by the PV, that block will be recorded on the blockchain as proof of
        cheating and the offending PV will be blacklisted from the network. Malicious blocks may include the
        miscalculation of balances, invalid signatures, or incorrect scheduling.
      </p>
      <p>
        For other network issues the PV may experience such as performance bottlenecks, unexpectedly dropping offline,
        and so on, the network will simply switch over to the next PV on the schedule. These type of issues would not
        result in the blacklisting of the PV since certain network disruptions are expected in a peer-to-peer
        architecture.
      </p>
      <p>
        The decision of whether or not to skip a PV is determined by consensus agreement by the CVs. Additionally, CVs
        votes on whether or not to skip a PV are weighted equally and not weighted by boost.
      </p>

      <DocImage alt="schedule adjustments" maxWidth={700} src={ScheduleAdjustments} />

      <p>
        When a majority of CVs vote to skip the PV during its turn, all CVs must reach consensus on exactly which block
        the next PV should take over. This is because in the middle of each turn, all CVs are not guaranteed to be
        perfectly in sync and may have blockchains of varying length. The process for switching to a new PV before the
        turn has finished is described in detail below.
      </p>
      <p>
        At the beginning of each turn when a new PV takes over, each CV will keep an independent record of all other CVs
        voting statuses. If a CV finds an issue with the PV (performance, error, offline, etc...) the CV will set its
        status to <b>halt requested</b> and broadcast that message out to all other validators.
      </p>

      <DocImage alt="halt requested" maxWidth={900} src={HaltRequested} />

      <p>
        When a majority of halt requests are received from the other CVs it will trigger the receiving CV to halt
        production of their blockchain. After stopping production that CV will set its own status to{' '}
        <b>blockchain halted</b> and broadcast that message along with the block number of its HEAD block (its last
        block before halting) out to all other CVs.
      </p>

      <DocImage alt="blockchain halted" maxWidth={800} src={BlockchainHalted} />

      <p>
        All CVs will follow similar logic resulting in each CV receiving the HEAD block from its peers. When the
        majority of blockchain halted requests have been received, the CVs may begin the{' '}
        <strong>syncing process</strong>. This involves first calculating the longest blockchain.
      </p>

      <DocImage alt="longest blockchain" maxWidth={500} src={LongestBlockchain} />

      <p>
        Once the longest blockchain has been determined, all other CVs will sync their own blockchains up to that block.
      </p>

      <DocImage alt="syncing blockchains" maxWidth={600} src={SyncingBlockchains} />

      <p>
        Note that the receiving CV only needs a majority of responses from the other CVs before syncing. This is because
        once a majority of responses have been received, all unknown responses would be from a minority of peers. It
        would therefore be impossible for that minority to have any longer blockchain given that a majority consensus
        needs reached in order to append a block to the blockchain, which would be impossible given the status of the
        halted CVs where each of their HEAD blocks are known.
      </p>
      <p>
        Once synced, CVs will send out a <b>sync switch</b> request. When the majority of CVs receive this they will all
        switch over to the new PV together.
      </p>

      <DocImage alt="last step" maxWidth={900} src={LastStep} />
    </DocContainer>
  );
};

export default GuideScheduleAdjustments;
