const HelloWorld: {[isoLangCode: string]: string} = {
  ar: 'مرحبًا بالعالم',
  az: 'Salam Dünya',
  bn: 'স্বাগতম বিশ্ব',
  bs: 'Zdravo Svijete',
  da: 'Hej Verden',
  de: 'Hallo Welt',
  el: 'Γεια σου κόσμε',
  en: 'Hello World',
  es: 'Hola Mundo',
  et: 'Tere Maailm',
  eu: 'Kaixo Mundua',
  fa: 'سلام دنیا',
  fi: 'Hei maailma',
  fj: 'Bula Vuravura',
  fr: 'Bonjour monde',
  gu: 'કેમ છો દુનિયા',
  he: 'שלום עולם',
  hi: 'नमस्ते दुनिया',
  hr: 'Pozdrav svijetu',
  id: 'Halo Dunia',
  ig: 'Ndewo Ụwa',
  it: 'Ciao Mondo',
  ja: 'こんにちは世界',
  kn: 'ನಮಸ್ಕಾರ ಪ್ರಪಂಚ',
  ko: '안녕 세상아',
  ku: 'Silav Dinya',
  ln: 'Mbote Mokili',
  lt: 'Labas Pasauli',
  mk: 'Здраво Свету',
  mr: 'नमस्कार जग',
  nl: 'Hallo Wereld',
  no: 'Hallo Verden',
  ps: 'سلام نړی',
  pt: 'Olá mundo',
  ru: 'Привет мир',
  sa: 'नमस्कारः जीवलोक',
  sk: 'Zdravo Svete',
  sr: 'Хало Свет',
  sv: 'Hej Värld',
  sw: 'Habari Dunia',
  ta: 'ஹலோ வேர்ல்ட்',
  te: 'హలో ప్రపంచం',
  th: 'สวัสดีโลก',
  tl: 'Kamusta Mundo',
  tr: 'Merhaba Dünya',
  uk: 'Привіт світе',
  ur: 'ہیلو ورلڈ',
  vi: 'Xin chào thế giới',
  yo: 'Mo ki Ile Aiye',
  zh: '你好 世界',
};

export const defaultHelloWorld = HelloWorld.en;

export const HelloWorldKeys = Object.keys(HelloWorld);

export default HelloWorld;
