const HelloWorld: {[isoLangCode: string]: string} = {
  af: 'Hello Wêreld',
  am: 'ሰላም ልዑል',
  an: 'Ola Mundo',
  ar: 'مرحبًا بالعالم',
  az: 'Salam Dünya',
  be: 'Прывітанне Сусвет',
  bn: 'স্বাগতম বিশ্ব',
  bs: 'Zdravo Svijete',
  bg: 'Здравей свят',
  ca: 'Hola món',
  cn: '你好，世界',
  cs: 'Ahoj světe',
  cy: 'Helo Byd',
  da: 'Hej Verden',
  de: 'Hallo Welt',
  fy: 'Hallo wrâld',
  el: 'Γεια σου κόσμε',
  en: 'Hello World',
  es: 'Hola Mundo',
  et: 'Tere Maailm',
  eo: 'Saluton mondo',
  eu: 'Kaixo Mundua',
  fa: 'سلام دنیا',
  fi: 'Hei maailma',
  fj: 'Bula Vuravura',
  fr: 'Bonjour monde',
  ga: 'Dia duit an Domhan',
  gd: 'Hàlo a Shaoghail',
  gl: 'Ola Mundo',
  gu: 'કેમ છો દુનિયા',
  he: 'שלום עולם',
  hi: 'नमस्ते दुनिया',
  hr: 'Pozdrav svijetu',
  is: 'Halló heimur',
  ha: 'Sannu Duniya',
  ht: 'Bonjou Mondyal',
  hu: 'Helló Világ',
  hy: 'Բարեւ աշխարհ',
  id: 'Halo Dunia',
  ig: 'Ndewo Ụwa',
  it: 'Ciao Mondo',
  ja: 'こんにちは世界',
  ka: 'Გამარჯობა მსოფლიო',
  kk: 'Сәлем Әлем',
  km: 'សួស្តី​ពិភពលោក',
  kn: 'ನಮಸ್ಕಾರ ಪ್ರಪಂಚ',
  ko: '안녕 세상아',
  ku: 'Silav Dinya',
  ky: 'салам дүйнө',
  la: 'salve Orbis Terrarum',
  lb: 'Moien Welt',
  ln: 'Mbote Mokili',
  lt: 'Labas Pasauli',
  lo: 'ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ',
  lv: 'Sveika pasaule',
  mk: 'Здраво Свету',
  ml:'ഹലോ വേൾഡ്',
  mr: 'नमस्कार जग',
  mi: 'Kia Ora Ao',
  mn: 'Сайн байна уу ертөнц',
  ms: 'Hai dunia',
  mt: 'Hello dinja',
  my: 'မင်္ဂလာပါကမ္ဘာလောက',
  ne: 'नमस्कार संसार',
  nl: 'Hallo Wereld',
  no: 'Hallo Verden',
  ny: 'Moni Dziko Lapansi',
  pl: 'Witaj świecie',
  ps: 'سلام نړی',
  pt: 'Olá mundo',
  ru: 'Привет мир',
  ro: 'Salut Lume',
  sa: 'नमस्कारः जीवलोक',
  sd: 'هيلو دنيا',
  si: 'හෙලෝ වර්ල්ඩ්',
  sk: 'Zdravo Svete',
  sl: 'Pozdravljen, svet',
  sm: 'Talofa lalolagi',
  sn: 'Mhoro Nyika',
  so: 'Waad salaaman tihiin aduunka',
  sq: 'Përshendetje Botë',
  st: 'Lefatše Lumela',
  su: 'Halo Dunya',
  sr: 'Хало Свет',
  sv: 'Hej Värld',
  sw: 'Habari Dunia',
  ta: 'ஹலோ வேர்ல்ட்',
  te: 'హలో ప్రపంచం',
  tg: 'Салом Ҷаҳон',
  th: 'สวัสดีโลก',
  tl: 'Kamusta Mundo',
  tr: 'Merhaba Dünya',
  uk: 'Привіт світе',
  ur: 'ہیلو ورلڈ',
  uz: 'Salom Dunyo',
  vi: 'Xin chào thế giới',
  xh: 'Molo Lizwe',
  yo: 'Mo ki Ile Aiye',
  yi: 'העלא וועלט',
  za: 'Salam dünya',
  zu: 'Sawubona Mhlaba',
  zh: '你好 世界'
};

export const defaultHelloWorld = HelloWorld.en;

export const HelloWorldKeys = Object.keys(HelloWorld);

export default HelloWorld;
