const HelloWorld: {[isoLangCode: string]: string} = {
  am: 'ሰላም አለም',
  ar: 'مرحبًا بالعالم',
  az: 'Salam Dünya',
  be: 'Прывітанне свет',
  bn: 'স্বাগতম বিশ্ব',
  bs: 'Zdravo Svijete',
  da: 'Hej Verden',
  de: 'Hallo Welt',
  el: 'Γεια σου κόσμε',
  en: 'Hello World',
  es: 'Hola Mundo',
  et: 'Tere Maailm',
  eu: 'Kaixo Mundua',
  fa: 'سلام دنیا',
  fi: 'Hei maailma',
  fj: 'Bula Vuravura',
  fr: 'Bonjour monde',
  gu: 'કેમ છો દુનિયા',
  he: 'שלום עולם',
  hi: 'नमस्ते दुनिया',
  hr: 'Pozdrav svijetu',
  hu: 'Helló világ',
  hy: 'Բարեւ աշխարհ',
  id: 'Halo Dunia',
  ig: 'Ndewo Ụwa',
  it: 'Ciao Mondo',
  ja: 'こんにちは世界',
  jv: 'Halo Jagad',
  ki: 'Ũhoro thîî',
  kn: 'ನಮಸ್ಕಾರ ಪ್ರಪಂಚ',
  ko: '안녕 세상아',
  ku: 'Silav Dinya',
  ln: 'Mbote Mokili',
  lt: 'Labas Pasauli',
  lv: 'Sveika pasaule',
  mk: 'Здраво Свету',
  ml: 'ഹലോ വേൾഡ്',
  mr: 'नमस्कार जग',
  ms: 'Hai Dunia',
  nd: 'Yebo Mhlaba',
  ne: 'नमस्कार संसार',
  nl: 'Hallo Wereld',
  no: 'Hallo Verden',
  or: 'ନମସ୍କାର ବିଶ୍ୱବାସି',
  pa: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਸੰਸਾਰ',
  ps: 'سلام نړی',
  pt: 'Olá mundo',
  ro: 'Salut Lume',
  ru: 'Привет мир',
  sa: 'नमस्कारः जीवलोक',
  sd: 'هيلو دنيا',
  si: 'හෙලෝ ලෝකය',
  sk: 'Zdravo Svete',
  sl: 'Pozdravljen svet',
  sq: 'Përshendetje Botë',
  sr: 'Здраво свете',
  sv: 'Hej Värld',
  sw: 'Habari Dunia',
  ta: 'உலகிருக்கு வணக்கம்',
  te: 'హలో ప్రపంచం',
  th: 'สวัสดีโลก',
  tl: 'Kamusta Mundo',
  tn: 'Dumelang Lefatshe',
  tr: 'Merhaba Dünya',
  uk: 'Привіт світе',
  ur: 'ہیلو ورلڈ',
  vi: 'Xin chào thế giới',
  yi: 'העלא וועלט',
  yo: 'Mo ki Ile Aiye',
  zh: '你好 世界',
};

export const defaultHelloWorld = HelloWorld.en;

export const HelloWorldKeys = Object.keys(HelloWorld);

export default HelloWorld;
