export const TeamPathname = {
  all: 'All',
  backEndDevelopers: 'Back-End-Developers',
  community: 'Community',
  design: 'Design',
  devOps: 'DevOps',
  discordManagers: 'Discord-Managers',
  dotnetCore: 'NET-Core',
  frontEndDevelopers: 'Front-End-Developers',
  kotlinSDK: 'Kotlin-SDK',
  marketing: 'Marketing',
  newUserOperations: 'New-User-Operations',
  payments: 'Payments',
  penetrationTesting: 'Penetration-Testing',
  projectProposals: 'Project-Proposals',
  qa: 'QA',
  redditModerators: 'Reddit-Moderators',
  research: 'Research',
  security: 'Security',
  youtube: 'YouTube',
};
